# Settings

CSV_COLUMNS = [
    'proprietary_name',
    'proprietary_names_additional',
    'establishment_type',
    'establishment_types_additional',
    'registration_number',
    'registration_fei_number',
    'registration_status_code',
    'registration_initial_importer_flag',
    'registration_expiry_date_year',
    'registration_name',
    'registration_address_line_1',
    'registration_address_line_2',
    'registration_city',
    'registration_state_code',
    'registration_iso_country_code',
    'registration_zip_code',
    'registration_postal_code',
    'registration_us_agent',
    'registration_us_agent_name',
    'registration_us_agent_business_name',
    'registration_owner_operator_firm_name',
    'registration_owner_operator_owner_operator_number',
    'pma_number',
    'k_number',
    'products_product_code',
    'products_created_date',
    'products_owner_operator_number',
    'products_exempt',
    'products_openfda_device_name',
    'products_openfda_medical_specialty_description',
    'products_openfda_regulation_number',
    'products_openfda_device_class',
    'products_additional'
    ]
